# Generated by Django 4.1.1 on 2022-10-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='password',
            new_name='login_password',
        ),
    ]
