# Generated by Django 4.1.1 on 2022-10-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_rename_password_data_login_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='login_password',
            new_name='password',
        ),
    ]
